<a href="https://colab.research.google.com/github/zohafatimadev/ACIP/blob/main/ACIP_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1


Write a NumPy program to create an array of all even integers from 30 to 70.

In [10]:
import numpy as np

even_array = np.arange(30, 72, 2)
print(even_array)


[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Question 2

Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.

In [4]:
import numpy as np

random_array = np.random.randn(15)
print(random_array)


[-0.04826575 -0.31710548  0.52655599  1.38739656  0.06227877  0.0542635
  0.93943631 -0.05741296  0.50326878 -0.18057251 -0.91410557  0.3271262
 -0.60079198  0.49620984  1.40825371]


Question 3

How to compute the cross-product of two matrices in NumPy?

In [5]:
import numpy as np

# Assuming A and B are two matrices
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

cross_product = np.cross(A, B)
print(cross_product)


[[ 0.24487084  0.61484856 -0.32153652]
 [-0.38697887  0.29875912  0.03337454]
 [-0.34211734  0.1867381   0.29930705]]


Question 4

How to compute the determinant of an array using NumPy?

In [6]:
import numpy as np

# Assuming mat is the matrix
mat = np.random.rand(3, 3)

determinant = np.linalg.det(mat)
print(determinant)


0.00822752690388388


Question 5

How to create a 3x3x3 array with random values using NumPy?

In [7]:
import numpy as np

random_3d_array = np.random.rand(3, 3, 3)
print(random_3d_array)


[[[0.56429836 0.27365128 0.9113552 ]
  [0.863845   0.55908095 0.08135385]
  [0.41320194 0.54150873 0.11416116]]

 [[0.32512374 0.7313884  0.11334836]
  [0.62809551 0.24694547 0.50391748]
  [0.45758133 0.75602256 0.94298822]]

 [[0.73050803 0.10398222 0.45146018]
  [0.47935773 0.53048418 0.82252432]
  [0.85218257 0.6906599  0.48884044]]]


Question 6

How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?

In [8]:
import numpy as np

random_5x5_array = np.random.rand(5, 5)
min_value = np.min(random_5x5_array)
max_value = np.max(random_5x5_array)

print("Minimum value:", min_value)
print("Maximum value:", max_value)


Minimum value: 0.025308412218079668
Maximum value: 0.9521290303133434


Question 7

How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?

In [9]:
import numpy as np

# Assuming arr is the array
arr = np.random.rand(3, 5)

mean_values = np.mean(arr, axis=1)
std_deviation_values = np.std(arr, axis=1)
variance_values = np.var(arr, axis=1)

print("Mean along second axis:", mean_values)
print("Standard Deviation along second axis:", std_deviation_values)
print("Variance along second axis:", variance_values)


Mean along second axis: [0.55467687 0.43901813 0.47792876]
Standard Deviation along second axis: [0.34874109 0.36351597 0.29486434]
Variance along second axis: [0.12162034 0.13214386 0.08694498]
